# Generated by Django 5.1.1 on 2024-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "ingredients",
                    models.CharField(
                        help_text="Separate each ingredient with a comma",
                        max_length=500,
                    ),
                ),
                ("cooking_time", models.IntegerField()),
                ("difficulty", models.CharField(editable=False, max_length=20)),
                ("instructions", models.TextField()),
            ],
        ),
    ]
